[package]
name = "dprint-core"
description = "Core formatter for dprint."
keywords = ["formatting", "formatter"]
version = "0.1.0"
authors = ["David Sherret <dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/dsherret/dprint/tree/master/packages/rust-core"
repository = "https://github.com/dsherret/dprint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
