language: rust
node_js:
  - 10
before_install:
  - nvm install 10
  - nvm use 10
  - node -v
  - rustup target add wasm32-unknown-unknown
install:
  - yarn install
  - yarn bootstrap
script:
  - yarn build
  - yarn test
env:
  - CI=true
