[package]
name = "dprint"
version = "0.2.2"
authors = ["Bartek Iwańczuk <biwanczuk@gmail.com>", "David Sherret<dsherret@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint."
repository = "https://github.com/dprint/dprint"

[dependencies]
clap = "2.33.0"
dprint-core = { path = "../rust-core", version = "0.14.0" }
dprint-plugin-typescript = { path = "../rust-dprint-plugin-typescript", version = "0.13.1" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
rayon = "1.1"
