[package]
name = "dprint"
version = "0.1.4"
authors = ["Bartek Iwańczuk <biwanczuk@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Binary for dprint."
repository = "https://github.com/dsherret/dprint"

[dependencies]
clap = "2.33.0"
dprint-core = { path = "../rust-core", version = "0.13.0" }
dprint-plugin-typescript = { path = "../rust-dprint-plugin-typescript", version = "0.10.1" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
